export type Track = { id: string; slug: string; title: string; soundcloudUrl?: string; embedUrl?: string; audioSrc: string; yearLabel: string; publishedLabel: string; duration?: string; shortText: string; longText: string; tags: string[]; coverImage?: string; coverHint?: string; featured?: boolean; };

type TrackSeed = Omit<Track, "audioSrc"> & { audioFile?: string };

const seedTracks: TrackSeed[] = [
  {"id":"B02","slug":"a-walk-in-zeeland","title":"A WALK IN ZEELAND","yearLabel":"2005","publishedLabel":"Birth era","shortText":"Zeeland at sunset: canals, distance, solitude and a path that keeps wandering.","longText":"This piece is tied to a solitary walk through Zeeland, between city edges and canals at sunset. It carries the feeling of being lost in life's meanders, with beauty and trouble moving side by side.","tags":["birth era","horizon","walk"],"coverHint":"Wind, distance and first horizon lines.","coverImage":"/images/tracks/a-walk-in-zeeland.png","featured":true},
  {"id":"B03","slug":"foolfoule","title":"FOOLFOULE","yearLabel":"2006","publishedLabel":"Birth era","shortText":"Rush-hour pressure: towers, crowds and people moving like robots.","longText":"This piece comes from the feeling of being caught in a large city's rush-hour crowd: skyscrapers above, pressure on every side, and people moving through the routine like robots.","tags":["birth era","playful","raw"],"coverHint":"Crooked momentum, early sparks.","coverImage":"/images/tracks/foolfoule.png"},
  {"id":"B04","slug":"jazzypling","title":"JAZZYPLING","yearLabel":"2006","publishedLabel":"Birth era","shortText":"Dark alleys, basement jazz and corners that feel slightly unsafe.","longText":"The scene behind this piece is nocturnal and urban: dark alleys, jazz played below street level, and those questionable corners where curiosity and caution arrive together.","tags":["birth era","groove","curiosity"],"coverHint":"A playful ping in the early archive.","coverImage":"/images/tracks/jazzypling.png"},
  {"id":"B05","slug":"play-it","title":"PLAY IT","yearLabel":"2008","publishedLabel":"Birth era","shortText":"Work, rules, the suit and the commute: the daily loop asking to be obeyed.","longText":"This piece belongs to the world of work, the suit, the commute and the metro-work-sleep rhythm: follow the rules, do what is expected, and keep the machine moving.","tags":["birth era","direct","momentum"],"coverHint":"Early motion asking to be repeated.","coverImage":"/images/tracks/play-it.png"},
  {"id":"01","slug":"rise","title":"RISE","soundcloudUrl":"https://soundcloud.com/misway/rise","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/rise&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2012","publishedLabel":"Older era","duration":"3:58","shortText":"Success imagined as a mountain ascent and the view from the summit.","longText":"The image behind this piece is an ascent: effort, height, success, and the moment when the landscape opens from the top of a mountain.","tags":["early","uplift","shadow"],"coverHint":"dark ascent","coverImage":"/images/tracks/rise.png"},
  {"id":"02","slug":"blossoming","title":"BLOSSOMING","soundcloudUrl":"https://soundcloud.com/misway/blossoming","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/blossoming&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2013","publishedLabel":"Older era","duration":"7:02","shortText":"Confidence at full intensity: speed, extreme sport and adrenaline.","longText":"This piece holds a period of confidence pushed to its peak, with the physical rush of extreme sports, risk and adrenaline.","tags":["early","organic","longform"],"coverHint":"dim bloom","coverImage":"/images/tracks/blossoming.png"},
  {"id":"03","slug":"ethnic-stick","title":"ETHNIC STICK","soundcloudUrl":"https://soundcloud.com/misway/ethnic-stick","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/ethnic-stick&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2013","publishedLabel":"Older era","duration":"4:39","shortText":"Africa calling through rhythm, roots, values and the search for meaning.","longText":"This piece is connected to Africa and to questions of roots, values and the meaning of life. Its title also carries the proximity between the ethnic and the ethical.","tags":["rhythm","texture","ritual"],"coverHint":"earth pulse","coverImage":"/images/tracks/ethnic-stick.png"},
  {"id":"04","slug":"minuit-moins-cinq","title":"MINUIT MOINS CINQ","soundcloudUrl":"https://soundcloud.com/misway/minuit-moins-cinq","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/minuit-moins-cinq&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2014","publishedLabel":"Older era","duration":"5:10","shortText":"A decision point: the hum of routine or the risk of another life.","longText":"Five minutes before midnight, a choice has to be made: remain inside the familiar hum of life, or accept the uncertainty and risk of another direction.","tags":["night","threshold","liminal"],"coverHint":"late midnight","coverImage":"/images/tracks/minuit-moins-cinq.png","featured":true},
  {"id":"05","slug":"perdue","title":"PERDUE","soundcloudUrl":"https://soundcloud.com/misway/misway-2021-moins-cinq","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/misway-2021-moins-cinq&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2021","publishedLabel":"Older era","duration":"6:33","shortText":"Connection fading: a relationship, a shared world, a person becoming distant.","longText":"This piece comes from the moment when a relationship, a shared life and the person beside you begin to fade. The loss is gradual before it becomes visible.","tags":["transition","fading","relationship"],"coverHint":"A shared world slowly leaving the frame.","coverImage":"/images/tracks/perdue.png"},
  {"id":"06","slug":"morne-et","title":"MORNE, ET ?","soundcloudUrl":"https://soundcloud.com/misway/morne-et-1","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/morne-et-1&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2023","publishedLabel":"Vegetative era","duration":"3:29","shortText":"Grey comfort and returning nihilism beneath an artificial happiness.","longText":"This piece sits inside a life that can look comfortable and even happy while an older nihilism returns underneath. The question mark matters as much as the greyness.","tags":["grey","question","mid-era"],"coverHint":"fog and doubt","coverImage":"/images/tracks/morne-et.png"},
  {"id":"07","slug":"daymason","title":"DAYMASON","soundcloudUrl":"https://soundcloud.com/misway/daymason","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/daymason&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2023","publishedLabel":"Vegetative era","duration":"2:41","shortText":"The unsaid: something present beyond a complete or shared understanding.","longText":"This piece is connected to what remains unsaid and to the distance between a private perception and any complete, common understanding of it.","tags":["fragment","construction","2023"],"coverHint":"cold day build","coverImage":"/images/tracks/daymason.png","featured":true},
  {"id":"08","slug":"chailk","title":"CHAILK","soundcloudUrl":"https://soundcloud.com/misway/chailk","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/chailk&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2023","publishedLabel":"Vegetative era","duration":"2:20","shortText":"Starting again from zero: empty, flat and open enough to rebuild.","longText":"This piece marks a reset: returning to an empty, flat space where almost everything has disappeared and something can begin again.","tags":["dust","mark","surface"],"coverHint":"chalk in darkness","coverImage":"/images/tracks/chailk.png"},
  {"id":"09","slug":"time","title":"TIME","soundcloudUrl":"https://soundcloud.com/misway/time","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/time&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2023","publishedLabel":"Vegetative era","duration":"3:30","shortText":"The world seems to collapse; there is no time, and still time must be taken.","longText":"This piece holds a contradiction: the sense that the world is collapsing and time is missing, alongside the need to stop and take time anyway.","tags":["time","reflection","2023"],"coverHint":"clockless glow","coverImage":"/images/tracks/time.png"},
  {"id":"10","slug":"tantitom","title":"TANTITOM","soundcloudUrl":"https://soundcloud.com/misway/tantitom","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/tantitom&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2023","publishedLabel":"Vegetative era","duration":"2:59","shortText":"Colour, emotion and lightness returning after a flatter stretch.","longText":"This piece marks the return of colour, emotion and a certain lightness after a period that felt flatter and more muted.","tags":["coded","playful","burst"],"coverHint":"quirky pulse","coverImage":"/images/tracks/tantitom.png"},
  {"id":"11","slug":"neektareum","title":"NEEKTAREUM","soundcloudUrl":"https://soundcloud.com/misway/neektareum-1","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/neektareum-1&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2025","publishedLabel":"New era","duration":"2:32","shortText":"Responsibility returns: even from a wounded place, movement remains possible.","longText":"This piece turns around responsibility and agency: a person can be hurt or trapped and still retain the possibility of moving. The thought is not triumphant; the music darkens as it goes.","tags":["return","strange","2025"],"coverHint":"nectar glitch","coverImage":"/images/tracks/neektareum.png","featured":true},
  {"id":"12","slug":"asitis","title":"ASITIS","soundcloudUrl":"https://soundcloud.com/misway/asitis","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/asitis&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2025","publishedLabel":"New era","duration":"2:44","shortText":"Acceptance without celebration: seeing what is there and letting it stand.","longText":"I do not keep a single definitive story for this title. Today I hear it as a form of acceptance: not approval or surrender, simply the decision to look at what is there as it is.","tags":["recent","acceptance","bare"],"coverHint":"plain signal","coverImage":"/images/tracks/asitis.png"},
  {"id":"13","slug":"relative","title":"RELATIVE","soundcloudUrl":"https://soundcloud.com/misway/relative","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/relative&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2026","publishedLabel":"New era","duration":"3:04","shortText":"A changing point of view, where distance and relation alter what seems fixed.","longText":"The exact starting point is not recorded here. Today I hear the piece as a shift in perspective: what felt absolute becomes relative, and movement becomes possible again.","tags":["recent","relation","movement"],"coverHint":"orbital drift","coverImage":"/images/tracks/relative.png"},
  {"id":"14","slug":"overthink","title":"OVERTHINK","soundcloudUrl":"https://soundcloud.com/misway/overthink","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/overthink&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2026","publishedLabel":"New era","duration":"2:08","shortText":"Thought accumulating until reflection becomes pressure and overload.","longText":"The title is direct, while the original trigger is not documented here. Today I hear a mind circling faster and faster until thinking stops clarifying and starts producing noise.","tags":["recent","mental","loop"],"coverHint":"neural static","coverImage":"/images/tracks/overthink.png"},
  {"id":"15","slug":"hold-the-light","title":"HOLD THE LIGHT","soundcloudUrl":"https://soundcloud.com/misway/hold-the-light","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/hold-the-light&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2026","publishedLabel":"New era","duration":"2:42","shortText":"Holding on to a small light without pretending the dark has gone.","longText":"I no longer attach one fixed story to this piece. Today I hear the act of keeping something luminous alive: fragile, deliberate, and surrounded by shadow rather than protected from it.","tags":["recent","light","anchor"],"coverHint":"held glow","coverImage":"/images/tracks/hold-the-light.png","featured":true},
  {"id":"16","slug":"midnight-work","title":"MIDNIGHT WORK","soundcloudUrl":"https://soundcloud.com/misway/midnight-work","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/midnight-work&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2026","publishedLabel":"New era","duration":"5:27","shortText":"Night work as vision: solitude, concentration and a world built while others sleep.","longText":"The precise first impulse is not recorded here. Today I hear the particular focus of working at night, when solitude can become both pressure and a space in which another world takes shape.","tags":["recent","night","studio"],"coverHint":"midnight console","coverImage":"/images/tracks/midnight-work.png","featured":true},
  {"id":"17","slug":"telatelaba","title":"TELATELABA","soundcloudUrl":"https://soundcloud.com/misway/telatelaba","embedUrl":"https://w.soundcloud.com/player/?url=https%3A//soundcloud.com/misway/telatelaba&color=%23050505&auto_play=false&hide_related=false&show_comments=false&show_user=true&show_reposts=false&show_teaser=true&visual=false","yearLabel":"2026","publishedLabel":"New era","duration":"2:47","shortText":"Here, there, between the two: movement without a final side.","longText":"The title itself keeps changing position. Today I hear a piece about the in-between: never entirely here or there, but alive in the passage from one side to the other.","tags":["recent","in-between","movement"],"coverHint":"liminal passage","coverImage":"/images/tracks/telatelaba.png","featured":true},
  {"id":"18","slug":"le-monde-s-endort","title":"LE MONDE S’ENDORT","yearLabel":"2026","publishedLabel":"New era","shortText":"The outside world dims while the inner movement remains awake.","longText":"The exact origin is not documented here. Today I hear the moment when the visible world grows quiet and soft, while something inside refuses to sleep and continues moving.","tags":["recent","night","hush"],"coverHint":"The world dims, the inner signal stays awake.","coverImage":"/images/tracks/le-monde-s-endort.png","featured":true},
  {"id":"19","slug":"renee","title":"RENEE","yearLabel":"2026","publishedLabel":"New era","shortText":"A return to PERDUE, reworked without erasing its first wound.","longText":"RENEE revisits PERDUE. The material is reshaped and polished, but the point is not to clean away the earlier emotion; it is to let it return in another form.","tags":["new era","origin","sensitive"],"coverHint":"First light through rough texture.","coverImage":"/images/tracks/renee-sens.png"},
  {"id":"20","slug":"panthere","title":"PANTHERE","audioFile":"panthere.mp3","yearLabel":"2026","publishedLabel":"New era","shortText":"An A WALK IN ZEELAND rework: more intense, more polished and looking forward.","longText":"The first Zeeland composition remains inside PANTHERE, but the rework pushes it toward a denser and more mature form. Its emotional direction is acceptance without immobility: keeping the past in view while turning toward what comes next.","tags":["new era","horizon","walk"],"coverHint":"Wind, distance and next horizon lines.","coverImage":"/images/tracks/panthere.png","featured":true},
  {"id":"21","slug":"eteeaooete","title":"ÉTÉÉAOOÉTÉ","yearLabel":"2026","publishedLabel":"New era","shortText":"A dawn beach ritual where the lambda stays simple and the ocean grows immense.","longText":"This piece belongs to an ocean beach at summer dawn: a lambda ritual drawn from sand, stones, driftwood and foam, with immense waves nearby and a ceremonial simplicity that remains human.","tags":["new era","ocean","lambda","ritual","waves"],"coverHint":"Oceanic lambda ritual, salt haze and immense waves."},
  {"id":"22","slug":"eux-gainent","title":"EUX GAINENT","audioFile":"eux-gainent.mp3","yearLabel":"2026","publishedLabel":"New era","shortText":"Urban repetition behind glass: bodies training like a machine that forgot why.","longText":"The scene is a glass-fronted gym: athletes visible from the street, repeating their movements like robots under cold light. Performance becomes routine, and the city presses its alienation against the window.","tags":["new era","city","gym","robotic","repetition"],"coverHint":"Glass-front gym, fluorescent light and mechanical bodies."},
];

export const tracks: Track[] = seedTracks.map((track) => ({ ...track, audioSrc: `/audio/${track.audioFile ?? `${track.slug}.mp3`}` }));

export function getTrackBySlug(slug: string) { return tracks.find((track) => track.slug === slug); }

export const featuredTracks = tracks.filter((track) => track.featured);
